source 'https://rubygems.org'
gem "bulma-clean-theme", '0.12' #'0.7.2'
gem 'github-pages', group: :jekyll_plugins
#gem 'github-pages', '212', group: :jekyll_plugins
gem 'jekyll-feed', '0.15.1'
#gem 'kramdown', '2.3.0'
gem 'mercenary', '0.3.3'
#gem 'jekyll', '3.9.0'
#gem 'jekyll-seo-tag', '2.7.1'
gem 'jekyll-sass-converter', '1.5.2'
gem 'public_suffix', '4.0.6'
gem 'webrick'